### ISSUE TITLE
unit tests throw `java.net.MalformedURLException: unknown protocol: otpauth`

### ISSUE THREAD

**Issue by caddac** [ackbox/ackbox-totp#1]
I'm getting the error `java.net.MalformedURLException: unknown protocol: otpauth` both when trying to execute `authenticator.createQRCode("MyIssuer", member.username!!, secret)` and when running the unit tests in your project directly. 
Error is being thrown at https://github.com/ackbox/ackbox-totp/blob/c87554e4f954ae259058118eb7146b3bbb7e4cf3/src/main/kotlin/com/ackbox/totp/QRCodeFactory.kt#L88

Googling hasn't turned up anything of too much use. Can you please advise?

**Comment by trein** [comment]
It was a bug introduced by me. Thanks for calling that out. Fixed in master.

**Comment by mazine** [comment]
@trein The fix is not published to Maven Central yet, is it?

**Comment by trein** [comment]
Released in v1.0.1. It may take a few minutes to get it in [here](https://mvnrepository.com/artifact/com.ackbox/ackbox-totp)
